<?php

use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\editor\Entity\Editor;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
//use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function test_d8_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.test_d8':
      $output = '';
      $output .= '<h3>'.t('About').'</h3>';
      $output .= '<p>'.t('Please send help').'</p>';

      return $output;
  }
}

/**
 * Implements template_preprocess_html().
 */
// send settings to JS
function test_d8_preprocess_html(&$variables){
  $settings = \Drupal::config('test_d8.settings');
  $variables['#attached']['drupalSettings']['TestD8']['time_to_complete_test'] = $settings->get('time_to_complete_test');
  $variables['#attached']['drupalSettings']['TestD8']['number_of_questions'] = $settings->get('number_of_questions');
}



function test_d8_form_alter(&$form, FormStateInterface $form_state, $form_id){
  // Cela permet d'activer les fonctionnalités de ckeditor au sein de views dans certains/tous les champs..
 if ($form_id == 'views_ui_config_item_form' && !empty($form['options']['content'])) {
   $form['options']['content']['#editor'] = TRUE;
 }
}


function test_d8_node_presave(EntityInterface $entity) {

  // On vérifie qu'il s'agit de l'enregistrement
  // d'un contenu de type score
  if ( 'score' == $entity->getType() ) {

    // On récupère certaines informations du contenu
    // afin de constituer un titre parlant
    $testId = $entity->get('field_score_nid')->getString();
    $testThemeId = node_load($testId)->get('field_theme')->getString();
    $themeName = taxonomy_term_load($testThemeId)->getName();

    $scoreDate = format_date($entity->getCreatedTime(), 'format_date_classique');

    $scoreScore = $entity->get('field_score_result')->getString();

    $scoreUser = user_load($entity->getOwnerId());
    $scoreUserFirstName = $scoreUser->get('field_prenom')->getString();
    $scoreUserLastName = $scoreUser->get('field_nom')->getString();
    $scoreUserName = $scoreUserFirstName . ' ' . $scoreUserLastName;


    // On défini le nouveau titre
    $scoreTitle  = 'Test '. $themeName;
    $scoreTitle .= ' - '. $scoreUserName;
    $scoreTitle .= ' - ' . $scoreDate;
    $scoreTitle .= ' - Score : ' . $scoreScore . ' %';

    $entity->setTitle($scoreTitle);
  }
}

